// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZVWg1yePI6h-MC8yb43Z5j5aYJewPnA',
    appId: '1:820774086098:web:9aaf1e837b49ef735ed40b',
    messagingSenderId: '820774086098',
    projectId: 'sales-manager-c9007',
    authDomain: 'sales-manager-c9007.firebaseapp.com',
    storageBucket: 'sales-manager-c9007.appspot.com',
    measurementId: 'G-B6Z1JVSZ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzpENwzhjJSvqy-tixHLG6kWTvuHgSX8',
    appId: '1:820774086098:android:6fce5e047e24d6df5ed40b',
    messagingSenderId: '820774086098',
    projectId: 'sales-manager-c9007',
    storageBucket: 'sales-manager-c9007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_Xm-JuaE7AgDy1ueNgsxYWL9bd85y9U',
    appId: '1:820774086098:ios:6e54a4682b2596c75ed40b',
    messagingSenderId: '820774086098',
    projectId: 'sales-manager-c9007',
    storageBucket: 'sales-manager-c9007.appspot.com',
    iosClientId: '820774086098-762op1j537gr4n3gb46ndvktfj8g9he7.apps.googleusercontent.com',
    iosBundleId: 'com.sales.manager.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_Xm-JuaE7AgDy1ueNgsxYWL9bd85y9U',
    appId: '1:820774086098:ios:6e54a4682b2596c75ed40b',
    messagingSenderId: '820774086098',
    projectId: 'sales-manager-c9007',
    storageBucket: 'sales-manager-c9007.appspot.com',
    iosClientId: '820774086098-762op1j537gr4n3gb46ndvktfj8g9he7.apps.googleusercontent.com',
    iosBundleId: 'com.sales.manager.com',
  );
}
